### ISSUE TITLE
Add smooth collapsing instead of normal collapsiable pannel.

### ISSUE THREAD

**Issue by Chaitanyassr** [inclusive-design/website-cities#46]
feature request - 

under the section - what topic to explore ?
we have collapsiable items that are not collapsing smoothly. Instead we can have smooth collapsiable in it.
example - https://codepen.io/moudstar/pen/ZKVLPW
![Screenshot (237)](https://user-images.githubusercontent.com/30374226/79023547-34da6a80-7b9e-11ea-970b-b8e9a410efc9.png)

**Comment by greatislander** [comment]
@Chaitanyassr Thanks for taking the time to open this issue. We are no longer actively developing this website so we aren't adding any new features at this time.
