### ISSUE TITLE
Better alignment of Images

### ISSUE THREAD

**Issue by Nisarg-27** [inclusive-design/website-cities#55]
Blog > Co-design Session #3 Synthesis Report
https://cities.inclusivedesign.ca/ideas/co-design-session-3-synthesis/

Problem: 
On the above-mentioned page, the images are so big that it can't fit on a normal screen and it looks bad. 
I'm using a 13-inch laptop the images do not fit on my screen. 

Solution: 
There are 2 ways we can solve this problem and make them more attractive
1. Change the size of the image and re-align them side by side.
2. Add a carousel

Screenshots: 
![problem 2](https://user-images.githubusercontent.com/77735347/105209148-840eec00-5b6f-11eb-9715-a7be2eb9c98c.JPG)

![problem one](https://user-images.githubusercontent.com/77735347/105209153-85401900-5b6f-11eb-887a-4a47b72bda2e.JPG)

Note: The images are so big that it can't fit the screen.

**Comment by greatislander** [comment]
@Nisarg-27 Thanks for taking the time to open this issue. We are no longer actively developing this website so we aren't adding any new features at this time.

**Comment by Nisarg-27** [comment]
Thanks for letting me know @greatislander. But is there any other website by Inclusive Design Institute (IDI) that I can contribute to?

**Comment by greatislander** [comment]
@Nisarg-27 It's probably best to start the discussion and introduce yourself in our Matrix channel (https://matrix.to/#/#fluid-work:matrix.org?via=matrix.org). Also if you are interested in GSoC 2021, we aren't planning on being a mentor organization this year.
